### ISSUE TITLE
'bytes' object has no attribute 'hex'

### ISSUE THREAD

**Issue by iamale** [concise/v2f.py#1]
Here's a full log:

```python-traceback
$ python3.4 v2f.py  # same with 3.5 and 3.6
v2f (V2F_DIR=/home/ale/.v2f PID=19340) started
Traceback (most recent call last):
  File "v2f.py", line 92, in <module>
    main()
  File "v2f.py", line 88, in main
    u2fhid.run_uhid_event_loop()
  File "/home/ale/tmp/v2f.py/u2fhid.py", line 303, in run_uhid_event_loop
    uhid_generate_create2_event()
  File "/home/ale/tmp/v2f.py/u2fhid.py", line 121, in uhid_generate_create2_event
    name.hex(), phys.hex(), uniq.hex(), rd_size, bus,
AttributeError: 'bytes' object has no attribute 'hex'

v2f (V2F_DIR=/home/ale/.v2f PID=19340) ended
```

I'll look into it when I have more time, but maybe you have an idea what's wrong here?

**Comment by concise** [comment]
The code raises such exception in Python version <= 3.4 because I used the `bytes.hex()` [API][1] that was introduced since Python 3.5.  It should work in Python 3.5 and 3.6.

[1]: https://docs.python.org/3.5/library/stdtypes.html#bytes.hex

**Comment by iamale** [comment]
Oh, sorry, it does indeed work on 3.5 and 3.6, it's just that my `/usr/bin/python3` points to 3.4 again for some reason (even though I configured it to resolve to 3.6).

Maybe add a reminder to the README though? Like ![python-3.5+](https://img.shields.io/badge/python-3.5+-blue.svg) or a simple statement somewhere near that “pre-alpha stage” one.

**Comment by concise** [comment]
Yep!  I just updated the README accordingly.  Thanks for the nice suggestion!

**Comment by iamale** [comment]
Neat! Another thing I found out is that while it plays well with Chrome, it doesn't work at all with [u2f4moz](https://github.com/prefiks/u2f4moz) for Firefox which uses hidraw APIs that are unsupported by v2f, apparently. Any plans to support them too?

**Comment by concise** [comment]
Good catch.  I only implemented a subset of the U2F spec.  Unfortunately, I don't have a plan on refactoring the codebase and supporting full U2F anytime soon since life becomes too busy =(
